# Generated by Django 6.0.4 on 2026-04-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="pdf_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="course",
            name="video_url",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
